//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcassin.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarcassinEntities1 : DbContext
    {
        public MarcassinEntities1()
            : base("name=MarcassinEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<ChatRoom> ChatRooms { get; set; }
        public virtual DbSet<Competence> Competences { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Message2> Message2 { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Relation_TCN> Relation_TCN { get; set; }
        public virtual DbSet<Relation_UCNi> Relation_UCNi { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
