//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcassin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message2
    {
        public int idMessage { get; set; }
        public string contenu { get; set; }
        public System.DateTime dateMessage { get; set; }
        public int ref_ChatRoom { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
    }
}
