//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcassin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation_TCN
    {
        public int ref_Tuteur { get; set; }
        public int ref_Note { get; set; }
        public int ref_Cours { get; set; }
    
        public virtual Cour Cour { get; set; }
        public virtual Note Note { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
