//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcassin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation_UCNi
    {
        public int ref_Utilisateur { get; set; }
        public int ref_Niveau { get; set; }
        public int ref_Competence { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual Niveau Niveau { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
