//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcassin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Relation_TCN = new HashSet<Relation_TCN>();
            this.Relation_UCNi = new HashSet<Relation_UCNi>();
            this.ChatRooms = new HashSet<ChatRoom>();
            this.Badges = new HashSet<Badge>();
            this.Cours = new HashSet<Cour>();
        }
    
        public int idUtilisateur { get; set; }
        public string prenomUtilisateur { get; set; }
        public string nomUtilisateur { get; set; }
        public int ageUtilisateur { get; set; }
        public string emailUtilisateur { get; set; }
        public string lienLinkedinUtilisateur { get; set; }
        public string motDePasseUtilisateur { get; set; }
        public bool estTuteur { get; set; }
        public bool estExterne { get; set; }
        public bool estValide { get; set; }
        public int ref_Ville { get; set; }
        public int ref_Entreprise { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation_TCN> Relation_TCN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation_UCNi> Relation_UCNi { get; set; }
        public virtual Ville Ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badge> Badges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cour> Cours { get; set; }
    }
}
